spring.application.name=KaushalPanjeeApp

# Eureka client config
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Unique instance ID (prevents overwrite)
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.ip-address}:${random.value}

spring.datasource.driver-class-name=org.postgresql.Driver

#Live
#server.port=8001
#server.port=0
#spring.datasource.url=jdbc:postgresql://10.247.221.19:5432/ddugky_audit

#Demo
server.port=7001
spring.datasource.url=jdbc:postgresql://localhost:5432/ddugky_audit_demo_05082025?serverTimezone=UTC

#Demo OCI
#spring.datasource.url=jdbc:postgresql://10.24.1.16:5432/ddugky_audit_demo?serverTimezone=UTC

#spring.datasource.username=postgres
#spring.datasource.password=postgres

spring.datasource.username=kaushalpanjee
spring.datasource.password=kaushalpanjee@123

spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

server.tomcat.threads.max=100
server.tomcat.threads.min-spare=20
server.tomcat.accept-count=100

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.show-sql=true

spring.mail.host=smtpgwhyd.nic.in
spring.web.cors.allowed-method = POST, GET

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

